version: "3"
services:
  app:
    restart: always
    build: . # Current directory!
    command: "python3 manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/codepred
    ports:
      - "9000:9000"
  